class People {
  static final contrubutors = [
    "Abhishek Doshi",
    "Adam Barth",
    "Alois Deniel",
    "Andrea Bizzotto",
    "Andrew Brogdon",
    "Bhavik Dodia",
    "Bhavik Makwana",
    "Chiziaruhoma",
    "Danielle Cox, The Flutterfly!",
    "Dhrumil Shah",
    "Dhruva",
    "Dipak Bari",
    "Dominik Roszkowski",
    "Felix Angelov",
    "Filip Hráček",
    "Johannes Milke",
    "Katarina Sheremet",
    "Kate Lovett",
    "Lara Martin",
    "Majid Hajian",
    "Manual Labarca",
    "Marcin Szalek",
    "Mariam Hasnany",
    "Marina",
    "Matt Rešetár",
    "Matt Sullivan",
    "Max Weber",
    "Merve Arslan",
    "Nawal Alhamwi",
    "Nikita Gandhi",
    "Nilay Yener",
    "Pascal Welsch",
    "Pawan Kumar",
    "Pooja Bhaumik",
    "Renuka Kelkar",
    "Robert Brunhage",
    "Romain Rastel",
    "Scott Stoll",
    "Simon Lightfoot",
    "Stefan Deconinck",
    "Sunny",
    "Tadas Petra",
    "Yash Adulkar",
    "Yogita Kumar",
    "creativecreatorormaybenot"
  ];
}
